### ISSUE TITLE
Issues with typing (backspace)

### ISSUE THREAD

**Issue by PassionateG1t** [LemmyNet/jerboa#194] opened 2022-07-14 18:38 UTC
When pressing the backspace several times, sometimes the last word would go back one character and attach itself to the one behind it.

Say I've written the following sentence:

> I can't believe you've done this

If I delete the last 5-6 characters, the following would happen:

> I can't believe you've**don** 

A temporary bypass is to select the characters that you want and delete them all at once.

**Comment by dessalines** [comment] 2022-07-14 19:27
This one is really difficult to beat, and incredibly annoying. I think it has something to do with the keyboard settings being messed up / wrong on jetpack-compose. I've tried a lot of ways to disable or mess with the Keyboard settings not working correctly, even after disabling auto-correct:

```kotlin
keyboardOptions = KeyboardOptions.Default.copy(
  capitalization = KeyboardCapitalization.Sentences,
  keyboardType = KeyboardType.Text,
  // autoCorrect = true,
),
```

**Comment by Kradyz** [comment] 2023-02-06 23:52
I agree, I also find this to be a bit of a nuissance! 

I have looked a bit into it. I found this answer from [stack exchange](https://stackoverflow.com/questions/69290080/android-jetpack-compose-textfield-disable-keyboard-auto-suggestions)  in which it is pointed out that 

This is confirmed in the [documentation on autoCorrect()](https://developer.android.com/reference/kotlin/androidx/compose/foundation/text/KeyboardOptions#autoCorrect()).

I have tested by changing setting 

```
keyboardType = keybordType.Email,
autoCorrect = false
```

for both lines ([here](https://github.com/dessalines/jerboa/blob/b0322af1b03b299997f5a095c5d668c4f716c067/app/src/main/java/com/jerboa/ui/components/common/InputFields.kt#L125) and [here](https://github.com/dessalines/jerboa/blob/b0322af1b03b299997f5a095c5d668c4f716c067/app/src/main/java/com/jerboa/ui/components/common/InputFields.kt#L137))

It does work! I don't know if this is an appropriate solution, as I don't know whether using the 'Email' type instead of the 'Text' type has any undesirable effects. But hopefully this is helpful.

**Comment by dessalines** [comment] 2023-02-10 18:17
Thanks! I'll test this to make sure it works as well. Could you comment on that stackoverflow issue, or create a new one, with this answer, for the backspace bug? Its a problem on all my apps that are using jetpack-compose, and there's little documentation about this bug anywhere.

**Comment by njmdietrich** [comment] 2023-06-17 00:50
At least on my phone, this issue actually occurs every time I try to delete more than one character in a word. Also, the autocorrect will sometimes get "stuck" if I try to edit a word in the middle of a sentence and subsequently keep editing that word even though I am just trying to continue typing the sentence.

**Comment by YoteZip** [comment] 2023-06-22 17:38
I'm still getting this in Jerboa 0.34 when typing with openboard and with the stock AOSP board, same symptoms as everyone else in here and in this issue: https://github.com/dessalines/jerboa/issues/748. I also have the behavior that njmdietrich mentions where it sometimes deletes a word and starts typing in the middle of my post instead of where my cursor is.

**Comment by shodanx2** [comment] 2023-06-22 20:31
Hello, 
I think I have this issue, it is very hard to describe and it doesn't happen consistently.
When going back to fix a typo of change a word and then bringing the cursor back to end of the text. I type something new, it overwrites the last word where I fixed the typo. As if the cursor was still where I fixed the typo and the keyboard was in "insert mode" sometimes each keypress will overwrite one letter of the previously edited word, sometimes the keypress will overwrite the entire word. 

Sometimes it does this 3/4 times in a row, it becomes easier to erase all text from the end back to where the typo was, and then rewrite the entire comment. 

I think I will just leave all error my errors in because editing my comments before posting is just too frustrating.

It does happen like 1/3 the time that I edit a comment I think.

**Comment by MarcoHannemann** [comment] 2023-06-27 09:30
I can confirm both problems with whitespaces lost after hitting backspace and the word removal @shodanx2 mentioned.

**Comment by asimons04** [comment] 2023-07-01 21:43
Same as described above.  It's extremely frustrating and pretty much is a dealbreaker for using Jerboa over the PWA.

Curious if it's just AOSP Keyboard that has the issue (that's all I'll use) or if other keyboards have this problem.

**Comment by MV-GH** [comment] 2023-07-04 07:50
https://issuetracker.google.com/issues/221636606

**Comment by MV-GH** [comment] 2023-07-04 08:36
@asimons04 Could i get your exact android version, + keyboard. Or from anyone experiencing this I'm trying to reproduce the issue first.

**Comment by shodanx2** [comment] 2023-07-04 09:05
![Screenshot_20230704-050245](https://github.com/dessalines/jerboa/assets/10621885/248f3cb9-1280-494a-b4e0-f6723d0c01ed)
![Screenshot_20230704-050428](https://github.com/dessalines/jerboa/assets/10621885/43ac29e3-0479-478f-abd6-ce2542e1673d)

**Comment by njmdietrich** [comment] 2023-07-04 09:24
> 

I am on Lineage for microG 20 (android 13) with the April security update. The keyboard is the AOSP keyboard version 13.

**Comment by asimons04** [comment] 2023-07-04 12:11
Device #1:  OnePlus 3 running LineageOS 18 (Android 9 based) , unknown OpenGapps version, and AOSP keyboard version 9.  I do not have an alternate keyboard to test with, but AOSP keyboard behaves as described in this issue when typing text anywhere in Jerboa.

Device #2:  Moto G Power (2022) on Android 11 (Stock) and de-Googled best I can. Google Play Services disabled and using AOSP keyboard version 11.  Temporarily re-enabling GBoard and setting that as the default on-screen keyboard, I was able to confirm Jerboa works as expected.  AOSP keyboard, though, is as described in this issue.

**Comment by MV-GH** [comment] 2023-07-04 12:25
Thanks, I'll see if I can reproduce this

**Comment by kuroi-usagi** [comment] 2023-07-04 12:40
Can confirm for another device:
One Plus Nord 2 5G on Android 12. Nothing changed on Google Play Services side. Just installed OpenBoard and using it.

**Comment by MV-GH** [comment] 2023-07-04 16:47
Alright can confirm, just installing a OASP keyboard makes it reproducable

**Comment by t-391** [comment] 2023-07-06 21:16
Hello, I can confirm that I have the same issue as described in the original post.

Device: Pixel 4A
OS: Lineage 20 (Android 13 Based)
Keyboard: AOSP

**Comment by theshatterstone** [comment] 2023-07-09 13:09
Hello. I also have the same issue as described in the original post.

Device: Xiaomi Redmi Note 11 Pro 5G (veux)
OS: SparkOS Vanilla (No GApps)
Keyboard: OpenBoard

**Comment by MV-GH** [comment] 2023-07-14 12:25
From my testing disabling `show correction suggestions` does prevent this from happening. For those wanting a immediate solution.
![image](https://github.com/dessalines/jerboa/assets/67873169/c2daa450-1213-46ed-a295-eb64ce02fc63)

**Comment by shodanx2** [comment] 2023-07-19 21:19
This issue has been resolved on my end since I last updated.

It was intermittent but happening often.

I have not had the issue at all since updating despite trying to make it happen.

Can anyone else confirm this is also fixed for you in the last update ?

**Comment by MV-GH** [comment] 2023-07-19 21:27
Jerboa update? Android update? keyboard update?

**Comment by theshatterstone** [comment] 2023-07-19 21:28
@shodanx2 I still had this issue. Until just now, when @MV-GH 's solution fixed it. It works for me now, but I needed to disable correction suggestions in OpenBoard (I didn't use them anyways so no big deal). So, thanks, @MV-GH, that fixed it. I'm also running the latest versions of Jerboa and OpenBoard from F-Droid.

**Comment by shodanx2** [comment] 2023-07-19 22:43
I'm still using gboard, I updated jerboa via fdroid to 0.0.40, it's been fixed since.

**Comment by MV-GH** [comment] 2023-07-19 22:49
Gboard never had this issue, are you sure?

**Comment by shodanx2** [comment] 2023-07-20 04:39
We might not have had the exact same issue. Mine would replace whole words after I made a correction earlier in the sentence. I would type just one character at end of the sentence, and the last word I modified would disappear entirely. This may be related to my heavy use of swiping. 

In anycase, it was doing it very frequently, now it does not do it at all.

**Comment by bobdanek** [comment] 2023-07-28 00:04
Still happening for me on 0.0.41 (GrapheneOS)

**Comment by MV-GH** [comment] 2023-07-28 00:05
Yeah it is issue with Compose itself, not something we can fix. All we can do is wait for a fix.

**Comment by shodanx2** [comment] 2023-07-28 08:31
Just updated to 0.0.41 and the very first comment I made, the problem came back!

**Comment by theshatterstone** [comment] 2023-07-30 09:02
@shodanx2 I'm using v0.0.41 with OpenBoard and using the fix by @MV-GH and it still works perfectly for me. Have you disabled correction suggestions?

**Comment by shodanx2** [comment] 2023-07-31 06:22
I'm using gboard with default settings, (except for adding a language and enabling swipe)

I don't use lemmy much anymore, however, the problem hasn't happenned since last I reported it.

**Comment by MV-GH** [comment] 2023-08-07 07:28
I finally got through to google, https://issuetracker.google.com/issues/294102838 , will monitor what happens

**Comment by meyou69** [comment] 2023-08-13 16:26
Can confirm. I also have this issue.

It's extremely annoying. I'm considering switching from using Lemmy entirely because of this issue

**Comment by theshatterstone** [comment] 2023-08-13 16:35
@meyou69 Can confirm that it is very annoying. I currently use a mix of Infinity for Lemmy and Liftoff.

**Comment by truenicoco** [comment] 2023-09-20 16:32
It's really bad. FWIW it happens on a vanilla LineageOS on a FP3+ and a custom lineageos on a mido. Both with the default LOS keyboard app.

**Comment by maltfield** [comment] 2024-01-05 20:45
+1 I've had this issue since I started using Jebora ~6 months ago. But I'll add that, in addition to spaces suddenly disappearing, sometimes when I try to backspace and correct a mistyped workd, it instead writes over some word that's much earlier, preventing me from being able to type additional words into the message. It's extremely frustrating.

**Comment by maltfield** [comment] 2024-01-05 23:32
As others have mentioned this is both extremely frustrating as a user and a developer because it's difficult to reproduce. I was playing around a bit and recorded this example of the bug. Note that when I go to the end of the paragraph and double-tap the enter/newline button on the keyboard, for some reason it replaces a few words back with the newlines.


https://github.com/dessalines/jerboa/assets/5026712/b1911370-e209-41fd-bafb-2d0d2e8bea16

**Comment by maltfield** [comment] 2024-01-06 00:09
In this screen recording I captured several events where clicking a backspace (or in two instances, typing some other character) caused a bunch of buggy behaviour:

1. the space between "dust and er" and "y" disappears @ 0:03 when I try to backspace away the "y"
1. the space between "dust and" and "e" disappears @ 0:03 when I try to backspace away the "e"
1. the space between "with the" and "win" disappears and "win" becomes "windc" when I only type the letter "c" @ 0:08
1. the space between "the" and "wind" disappears and "wind" becomes "windm" when I type the character "." @ 0:12
1. the space between "with" and "thewind" disappears when I backspace the character "d"
 

The fact that "win" becomes "wind" (and also note the highlighting of the word "_win" that includes the space before the word, does tell me that this is a bug related to autocorrect.

I should note that this bug only exists in Jebora. I use this same device with this same software keyboard on many other apps, and I've never experienced this in any other app.


https://github.com/dessalines/jerboa/assets/5026712/ed308de1-59d4-4325-9dea-abb99ca031e3

**Comment by shodanx2** [comment] 2024-01-06 00:23
This was exactly my experience as well. It has something to do with the
autocorrect and the space key.

Sometimes adding extra spaces after the corrected word will stop the bug
from triggering.

Often, I just erased everything back to the correction. Or I posted without
correction but then edited my post. That seemed to reset the bug.

Since my last update, I kicked out google out of my life as much as I
could. Now I use the florisboard. Unfortunately, autocorrect is not yet
functionnal. I have not observed this bug since.

On Friday, January 5, 2024, Michael Altfield ***@***.***>
wrote:
> In this screen recording I captured several events where clicking a
backspace (or in two instances, typing some other character) caused a bunch
of buggy behaviour:
>
> the space between "dust and er" and "y" disappears @ 0:03 when I try to
backspace away the "y"
> the space between "dust and" and "e" disappears @ 0:03 when I try to
backspace away the "e"
> the space between "with the" and "win" disappears and "win" becomes
"windc" when I only type the letter "c" @ 0:08
> the space between "the" and "wind" disappears and "wind" becomes "windm"
when I type the character "." @ 0:12
> the space between "with" and "thewind" disappears when I backspace the
character "d"
>
> The fact that "win" becomes "wind" (and also note the highlighting of the
word "_win" that includes the space before the word, does tell me that this
is a bug related to autocorrect.
>
> I should note that this bug only exists in Jebora. I use this same device
with this same software keyboard on many other apps, and I've never
experienced this in any other app.
>
>
https://github.com/dessalines/jerboa/assets/5026712/ed308de1-59d4-4325-9dea-abb99ca031e3
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.<
https://ci6.googleusercontent.com/proxy/ta0iMLYRJiZLs4H4EXN7SBzn76TIcFRpn5u8brA2K9EzQgr44EeeXi2ZqwHpxVeSu5cEWkmWzZTJeOWxg_eDUV5jRfMK4BxwJwy0za1SbqiRB-bnAj1gYphYsgJoDIeTCq1xLC24QTpPwdgQ2u1hYa8LhLGjnIBFHvFfX3caM4L8bAugVjKFNinfysjfes6C-0iYrDHw-ksndrmtDnD4RVFhYw-U6xhNWuT_DP6dUA=s0-d-e1-ft#https://github.com/notifications/beacon/ACRBHPOXHVCBNU6LA3ZEGYTYNCI3JA5CNFSM53TFUWF2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOOAC66FQ.gif>Message
ID: ***@***.***>

**Comment by maltfield** [comment] 2024-01-06 00:30
I've encountered numerous cases where posting and then trying to edit did not "reset" the bug. I was still unable to add content without it overriding a word. What I'd do:

1. I click edit to edit the comment.
2. I move the keyboard cursor to the end of the text
3. I type two newline characcters to start a new paragraph, and realize it replaced some word in the previous text above with newlines
4. I re-type the word that the bug deleted
5. GOTO 2

**Comment by MV-GH** [comment] 2024-01-06 00:45
Let me iterate some points I made before:
> I should note that this bug only exists in Jebora. I use this same device with this same software keyboard on many other apps, and I've never experienced this in any other app.
- This is a bug with the core basic text element, and every app made with the Compose Toolkit will be affected by it
- The only known workaround while still using a AOSP keyboard, is by disabling `show corrections suggestions` setting
- Any reproductions are not useful here, as the Android engineers that need to read this won't read this issue, instead I suggest you post this to the linked issue.
- I am aware this issue is extremely annoying, and its even more annoying that I am unable to fix due lacking the required specific domain knowledge. And the realization that this issue will most likely sink in the backlog as it doesn't affect Gboard and thus is not a priority. At this point it is more likely that any of the OASP keyboards apply a workaround.

**Comment by maltfield** [comment] 2024-01-06 00:48
@MV-GH sorry but what is Jetpack Compose Toolkit and how do I find out which of the apps that I have installed use it?

**Comment by MV-GH** [comment] 2024-01-06 00:56
https://developer.android.com/jetpack/compose
It is the new way of making Android apps, and is intended to replace the existing traditional view system.

>  And how do I find out which of the apps that I have installed use it?

https://medium.com/@callmeryan/a-developers-approach-to-identifying-jetpack-compose-usage-in-apps-978601e36de2
This article has some pointers.

> Jetpack Compose Toolkit super rare
It is not mature yet, which is probably why it is not popular yet.
But compose allows you to build cross platform (iOS, web, Android) apps
Which a longterm goal of Jerboa but which is not actively worked toward atm

At the top I mentioned some other issues that had related problems but with other keyboards or specific locales

**Comment by k4r4b3y** [comment] 2024-08-24 13:15
Still having this issue.  Installed Jerboa on GrapheneOS (latest), from F-droid repo (latest).  Quite annoying.  Frustrating.

**Comment by shodanx2** [comment] 2024-08-24 19:11
To anyone having this issue, I recommend changing your keyboard to one of
the open source one like Florisboard or futo's keyboard

On Saturday, August 24, 2024, Anark Karabey ***@***.***>
wrote:
> Still having this issue. Installed Jerboa on GrapheneOS (latest), from
F-droid repo (latest). Quite annoying. Frustrating.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.<
https://ci3.googleusercontent.com/meips/ADKq_NZtFYTiyRd4s22-JIvbO4_cnYVUQPhF2SnsBYnjY2oQJwrh4VfbS-TomlAIhlr9kfEo33JK22kpPVrzwM0X99-Hg7QRuPRjrM3eswvmCeaRrOtJuOIsewigUVQqwcBEy2_QNM-SpRfEBCG_EAsq37DC55bnxlEVwI-hg_AUXfobIE-7DpPIBlPhY8lf_TP715qin9XSX5XbospAsDOQeL6MQQgvPR6RzH7xvZX2HfzpLgs=s0-d-e1-ft#https://github.com/notifications/beacon/ACRBHPPCA4AMTG5HUDP2QPDZTCBQTA5CNFSM53TFUWF2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGORGLUM3A.gif>Message
ID: ***@***.***>

**Comment by k4r4b3y** [comment] 2024-08-25 10:19
@shodanx2 I am having the problem on GrapheneOS and on GrapheneOS's default keyboard.

**Comment by dessalines** [comment] 2024-08-27 20:16
@k4r4b3y Could you open up an issue on GrapheneOS's default keyboard? It seems like google has fixed most of these issues for jetpack-compose, and I can't replicate it on most open source keyboards.

I'm going to close this since this wasn't our issue, but something affecting jetpack compose in general.

**Closed by dessalines** 2024-08-27 20:16 UTC
Labels: bug, 3 - medium priority, onhold
