### ISSUE TITLE
Can't switch keyboards (or languages) while focused on (seemingly) any input field

### ISSUE THREAD

**Issue by Tmpod** [LemmyNet/jerboa#1610] opened 2024-08-03 23:12 UTC
### Jerboa Version

0.0.71

### Android Version + Phone

Android 12, Google Pixel 4a

### Describe The Bug

It seems impossible to switch virtual/screen keyboard (often used for switching between languages, like in OpenBoard/Heliboard, FUTO Keyboard, etc), while focused on (as far as I can tell) **any** input field in the app — the keyboard selection modal flashes really quickly and the virtual keyboard pops up again.

Here's a quick video demonstrating this:

https://github.com/user-attachments/assets/a0fd6f3f-144e-4385-80e8-3c0352246501

### To Reproduce

1. Go to "Search"
2. Focus the input field
3. Long press the spacebar (if your keyboard works like that; most do).
4. The system's modal will flash.

**Comment by MV-GH** [comment] 2024-08-04 19:02
I can repro, most likely caused by compose update.

**Comment by MV-GH** [comment] 2024-08-04 19:29
Ah the good news is that also fixed in a newer update.

**Closed** 2024-08-05 02:52 UTC
Labels: bug
